import { writeFile } from 'node:fs/promises';

/**
 * Write one `_gen/data/*.mjs` from imported problems. Every string goes through
 * JSON.stringify rather than a template literal, because imported text is not
 * ours to trust with backticks.
 */
export async function emitDataFile({ path, category, dir, intro, problems }) {
  const entries = problems.map((problem) => {
    const lines = [
      '    {',
      `      n: ${problem.n},`,
      `      title: ${JSON.stringify(problem.title)},`,
      `      slug: ${JSON.stringify(problem.slug)},`,
      `      difficulty: ${JSON.stringify(problem.difficulty)},`,
    ];

    if (problem.leetcode) lines.push(`      leetcode: ${JSON.stringify(problem.leetcode)},`);
    if (problem.source) lines.push(`      source: ${JSON.stringify(problem.source)},`);

    lines.push(
      `      pattern: ${JSON.stringify(problem.pattern)},`,
      `      complexity: ${JSON.stringify(problem.complexity)},`,
      `      statement: ${JSON.stringify(problem.statement)},`,
      `      examples: ${JSON.stringify(problem.examples)},`,
      `      constraints: ${JSON.stringify(problem.constraints ?? [])},`,
    );

    if (problem.followUp) lines.push(`      followUp: ${JSON.stringify(problem.followUp)},`);
    lines.push(`      stub: ${JSON.stringify(problem.stub)},`, '    },');
    return lines.join('\n');
  });

  const file = [
    '// Generated by _gen/import. Do not edit by hand - re-run the importer instead.',
    'export default {',
    `  category: ${JSON.stringify(category)},`,
    `  dir: ${JSON.stringify(dir)},`,
    `  intro: ${JSON.stringify(intro)},`,
    '  problems: [',
    ...entries,
    '  ],',
    '};',
    '',
  ].join('\n');

  await writeFile(path, file, 'utf8');
  return problems.length;
}
