/**
 * 92. Word Ladder   ·   Hard   ·   Graphs
 *
 * Given beginWord, endWord and a dictionary wordList, a transformation
 * sequence changes one letter at a time and every intermediate word must be in
 * wordList. Return the number of words in the shortest such sequence from
 * beginWord to endWord, counting both ends, or 0 when none exists. beginWord
 * does not need to be in wordList.
 *
 * Example 1:
 *   Input:  beginWord = "hit", endWord = "cog",
 *           wordList = ["hot", "dot", "dog", "lot", "log", "cog"]
 *   Output: 5          // hit -> hot -> dot -> dog -> cog
 *
 * Example 2:
 *   Input:  beginWord = "hit", endWord = "cog",
 *           wordList = ["hot", "dot", "dog", "lot", "log"]
 *   Output: 0          // "cog" is not in the list
 *
 * Constraints:
 *   - 1 <= beginWord.length <= 10 and endWord.length === beginWord.length
 *   - 1 <= wordList.length <= 5000
 *   - All words are lowercase, the same length, and unique
 *
 * Follow-up: Comparing every pair of words is O(n^2). Bucket by patterns like
 * h*t instead.
 *
 * Pattern:   BFS over words, neighbours generated by wildcard patterns
 * Target:    O(n * L^2) time with pattern buckets
 * LeetCode:  https://leetcode.com/problems/word-ladder/
 * Video:     https://www.youtube.com/watch?v=T0u5nwSA0w0&t=76283s  (21:11:23)
 */
export function ladderLength(beginWord: string, endWord: string, wordList: string[]): number {
  throw new Error('Not implemented');
}
